# To create an environment with this configuration, use the following command:
# conda env create -f environment.yaml

name: kaggle_titanic
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - altair
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - ipykernel
    

